spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    hostname: localhost

zuul:
  routes:
    users: /api/users/**
    recipes: /api/recipes/**

server:
  port: 8989

